// Generated by CoffeeScript 1.7.1
(function() {
  window.Movie || (window.Movie = {
    Models: {},
    Collections: {},
    Views: {},
    Routers: {}
  });

  $(document).ready(function() {
    return new Movie.Views.GameEntryView;
  });

}).call(this);
