// Generated by CoffeeScript 1.7.1
(function() {
  var _base,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Movie || (window.Movie = {});

  (_base = window.Movie).Services || (_base.Services = {});

  Movie.Services.CastService = (function(_super) {
    __extends(CastService, _super);

    function CastService() {
      this.messageError = __bind(this.messageError, this);
      this.messageSuccess = __bind(this.messageSuccess, this);
      return CastService.__super__.constructor.apply(this, arguments);
    }

    CastService.prototype.sendMessage = function(message) {
      var session;
      session = window.sessionID;
      return session.sendMessage('urn:x-cast:movie.quote.game', message, this.messageSuccess, this.messageError);
    };

    CastService.prototype.messageSuccess = function(e) {
      return console.log(e);
    };

    CastService.prototype.messageError = function(e) {
      return console.log(e);
    };

    return CastService;

  })(Backbone.View);

}).call(this);
