// Generated by CoffeeScript 1.7.1
(function() {
  var _base,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Movie || (window.Movie = {});

  (_base = window.Movie).Views || (_base.Views = {});

  Movie.Views.MultiplayerView = (function(_super) {
    __extends(MultiplayerView, _super);

    function MultiplayerView() {
      this.timer = __bind(this.timer, this);
      return MultiplayerView.__super__.constructor.apply(this, arguments);
    }

    MultiplayerView.prototype.initialize = function() {
      MultiplayerView.__super__.initialize.call(this);
      return this.$("h1.question").html("Waiting for Player 2 Game Will Start Shortly!");
    };

    MultiplayerView.prototype.timer = function() {
      this.count = this.count - 1;
      this.$('h1.timer').html("<h1>" + this.count + " seconds left!</h1>");
      if (this.count <= 0) {
        window.clearInterval(this.counter);
        this.counter = 0;
        this.$('h1.timer').html("<h1>Times Up!!</h1>");
        return new Movie.Views.GameResultView({
          attributes: {
            players: "multiplayer",
            correctAnswers: this.correctAnswers,
            totalQuestions: this.questionNumber,
            playerName: this.attributes.playerName
          }
        });
      }
    };

    return MultiplayerView;

  })(Movie.Views.GamePlayView);

}).call(this);
